python_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    data = [
        "//common/test_utils/common/tests/input:example_contract",
        "//common/test_utils/common/tests/output:contract_calendars_replaced"
    ],
    deps = [
        "//common/test_utils/endtoend",
        "//common/python:file_utils"
    ],
    labels = ["unit"],
)