python_library(
    name = "test_objects",
    srcs = [
        "postings_template.py",
        "sim_output.py"
    ],
    visibility = ["PUBLIC"]
)

filegroup(
    name = "test_data",
    srcs = [
        "failed_batch.json",
        "partially_failed_batch.json",
        "successful_batch.json"
    ],
    visibility = [
        "PUBLIC"
    ]
)
