python_library(
    name = "kafka",
    srcs = ["kafka.py"],
    visibility = ["PUBLIC"],
    deps = [ 
        "//third_party/python3:confluent-kafka",
        "//common/test_utils/performance/data_objects:data_objects",
    ]
)
