python_library(
    name = "generate_postings_sim_input",
    srcs = [
        "generate_postings_sim_input.py",
        "posting_instruction_batches.py",
    ],
    visibility = ["PUBLIC"]
)

filegroup(
    name = "test_data",
    srcs = [
        "test_profile.yaml",
        "sample_balance_update_event.json",
        "sample_wf_instantiation_event.json"
    ],
    visibility = [
        "PUBLIC"
    ]
)
