python_library(
    name = "helper",
    srcs = ["helper.py"],
    visibility = ["PUBLIC"],
    deps = [
        "//common/test_utils/postings:override_classes",
        "//common/test_utils/postings:posting_classes",
        "//common/test_utils/postings:postings_helper"
    ]
)
