# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthUpdateServiceAccountPermissionsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_account_id': 'str',
        'request_id': 'str',
        'items_to_add': 'list[str]',
        'items_to_remove': 'list[str]'
    }

    attribute_map = {
        'service_account_id': 'service_account_id',
        'request_id': 'request_id',
        'items_to_add': 'items_to_add',
        'items_to_remove': 'items_to_remove'
    }

    def __init__(self, service_account_id=None, request_id=None, items_to_add=None, items_to_remove=None):  # noqa: E501
        """AuthUpdateServiceAccountPermissionsRequest - a model defined in Swagger"""  # noqa: E501
        self._service_account_id = None
        self._request_id = None
        self._items_to_add = None
        self._items_to_remove = None
        self.discriminator = None
        if service_account_id is not None:
            self.service_account_id = service_account_id
        self.request_id = request_id
        if items_to_add is not None:
            self.items_to_add = items_to_add
        if items_to_remove is not None:
            self.items_to_remove = items_to_remove

    @property
    def service_account_id(self):
        """Gets the service_account_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501

        The ID of the service account that is to be updated. Required.  # noqa: E501

        :return: The service_account_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :rtype: str
        """
        return self._service_account_id

    @service_account_id.setter
    def service_account_id(self, service_account_id):
        """Sets the service_account_id of this AuthUpdateServiceAccountPermissionsRequest.

        The ID of the service account that is to be updated. Required.  # noqa: E501

        :param service_account_id: The service_account_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :type: str
        """

        self._service_account_id = service_account_id

    @property
    def request_id(self):
        """Gets the request_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501

        A unique string ID used to ensure the request is idempotent. Required.  Required.  # noqa: E501

        :return: The request_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this AuthUpdateServiceAccountPermissionsRequest.

        A unique string ID used to ensure the request is idempotent. Required.  Required.  # noqa: E501

        :param request_id: The request_id of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def items_to_add(self):
        """Gets the items_to_add of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501

        A list of items to be added to the list of service account permissions. Optional.  # noqa: E501

        :return: The items_to_add of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._items_to_add

    @items_to_add.setter
    def items_to_add(self, items_to_add):
        """Sets the items_to_add of this AuthUpdateServiceAccountPermissionsRequest.

        A list of items to be added to the list of service account permissions. Optional.  # noqa: E501

        :param items_to_add: The items_to_add of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :type: list[str]
        """

        self._items_to_add = items_to_add

    @property
    def items_to_remove(self):
        """Gets the items_to_remove of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501

        A list of items to be removed from the list of service account permissions. Optional.  # noqa: E501

        :return: The items_to_remove of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._items_to_remove

    @items_to_remove.setter
    def items_to_remove(self, items_to_remove):
        """Sets the items_to_remove of this AuthUpdateServiceAccountPermissionsRequest.

        A list of items to be removed from the list of service account permissions. Optional.  # noqa: E501

        :param items_to_remove: The items_to_remove of this AuthUpdateServiceAccountPermissionsRequest.  # noqa: E501
        :type: list[str]
        """

        self._items_to_remove = items_to_remove

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthUpdateServiceAccountPermissionsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthUpdateServiceAccountPermissionsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
