# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CalendarChangeCurrentCalendarPeriodRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_id': 'str',
        'calendar_id': 'str',
        'action': 'ChangeCurrentCalendarPeriodRequestAction',
        'action_timestamp': 'datetime'
    }

    attribute_map = {
        'request_id': 'request_id',
        'calendar_id': 'calendar_id',
        'action': 'action',
        'action_timestamp': 'action_timestamp'
    }

    def __init__(self, request_id=None, calendar_id=None, action=None, action_timestamp=None):  # noqa: E501
        """CalendarChangeCurrentCalendarPeriodRequest - a model defined in Swagger"""  # noqa: E501
        self._request_id = None
        self._calendar_id = None
        self._action = None
        self._action_timestamp = None
        self.discriminator = None
        self.request_id = request_id
        self.calendar_id = calendar_id
        self.action = action
        if action_timestamp is not None:
            self.action_timestamp = action_timestamp

    @property
    def request_id(self):
        """Gets the request_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501

        Unique ID that is used to identify the request.  Required.  # noqa: E501

        :return: The request_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this CalendarChangeCurrentCalendarPeriodRequest.

        Unique ID that is used to identify the request.  Required.  # noqa: E501

        :param request_id: The request_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def calendar_id(self):
        """Gets the calendar_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501

        ID of the calendar.  Required.  # noqa: E501

        :return: The calendar_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :rtype: str
        """
        return self._calendar_id

    @calendar_id.setter
    def calendar_id(self, calendar_id):
        """Sets the calendar_id of this CalendarChangeCurrentCalendarPeriodRequest.

        ID of the calendar.  Required.  # noqa: E501

        :param calendar_id: The calendar_id of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :type: str
        """
        if calendar_id is None:
            raise ValueError("Invalid value for `calendar_id`, must not be `None`")  # noqa: E501

        self._calendar_id = calendar_id

    @property
    def action(self):
        """Gets the action of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501


        :return: The action of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :rtype: ChangeCurrentCalendarPeriodRequestAction
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this CalendarChangeCurrentCalendarPeriodRequest.


        :param action: The action of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :type: ChangeCurrentCalendarPeriodRequestAction
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501

        self._action = action

    @property
    def action_timestamp(self):
        """Gets the action_timestamp of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501

        When to Roll to/Until when to Hold. Cannot be in the past. Defaults to the current system timestamp in UTC.  # noqa: E501

        :return: The action_timestamp of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._action_timestamp

    @action_timestamp.setter
    def action_timestamp(self, action_timestamp):
        """Sets the action_timestamp of this CalendarChangeCurrentCalendarPeriodRequest.

        When to Roll to/Until when to Hold. Cannot be in the past. Defaults to the current system timestamp in UTC.  # noqa: E501

        :param action_timestamp: The action_timestamp of this CalendarChangeCurrentCalendarPeriodRequest.  # noqa: E501
        :type: datetime
        """

        self._action_timestamp = action_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CalendarChangeCurrentCalendarPeriodRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CalendarChangeCurrentCalendarPeriodRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
