# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CalendarBatchGetCalendarEventsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'calendar_events': 'dict(str, CalendarCalendarEvent)'
    }

    attribute_map = {
        'calendar_events': 'calendar_events'
    }

    def __init__(self, calendar_events=None):  # noqa: E501
        """CalendarBatchGetCalendarEventsResponse - a model defined in Swagger"""  # noqa: E501
        self._calendar_events = None
        self.discriminator = None
        if calendar_events is not None:
            self.calendar_events = calendar_events

    @property
    def calendar_events(self):
        """Gets the calendar_events of this CalendarBatchGetCalendarEventsResponse.  # noqa: E501

        Maps the Calendar Event IDs to the requested Calendar Events.  # noqa: E501

        :return: The calendar_events of this CalendarBatchGetCalendarEventsResponse.  # noqa: E501
        :rtype: dict(str, CalendarCalendarEvent)
        """
        return self._calendar_events

    @calendar_events.setter
    def calendar_events(self, calendar_events):
        """Sets the calendar_events of this CalendarBatchGetCalendarEventsResponse.

        Maps the Calendar Event IDs to the requested Calendar Events.  # noqa: E501

        :param calendar_events: The calendar_events of this CalendarBatchGetCalendarEventsResponse.  # noqa: E501
        :type: dict(str, CalendarCalendarEvent)
        """

        self._calendar_events = calendar_events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CalendarBatchGetCalendarEventsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CalendarBatchGetCalendarEventsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
