# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CalendarUpdateCalendarRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_id': 'str',
        'calendar_id': 'str',
        'calendar': 'CalendarCalendar',
        'update_mask': 'ProtobufFieldMask'
    }

    attribute_map = {
        'request_id': 'request_id',
        'calendar_id': 'calendar_id',
        'calendar': 'calendar',
        'update_mask': 'update_mask'
    }

    def __init__(self, request_id=None, calendar_id=None, calendar=None, update_mask=None):  # noqa: E501
        """CalendarUpdateCalendarRequest - a model defined in Swagger"""  # noqa: E501
        self._request_id = None
        self._calendar_id = None
        self._calendar = None
        self._update_mask = None
        self.discriminator = None
        self.request_id = request_id
        self.calendar_id = calendar_id
        self.calendar = calendar
        self.update_mask = update_mask

    @property
    def request_id(self):
        """Gets the request_id of this CalendarUpdateCalendarRequest.  # noqa: E501

        The ID of the request used for idempotency.  Required.  # noqa: E501

        :return: The request_id of this CalendarUpdateCalendarRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this CalendarUpdateCalendarRequest.

        The ID of the request used for idempotency.  Required.  # noqa: E501

        :param request_id: The request_id of this CalendarUpdateCalendarRequest.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def calendar_id(self):
        """Gets the calendar_id of this CalendarUpdateCalendarRequest.  # noqa: E501

        The ID of the calendar that is to be updated.  Required.  # noqa: E501

        :return: The calendar_id of this CalendarUpdateCalendarRequest.  # noqa: E501
        :rtype: str
        """
        return self._calendar_id

    @calendar_id.setter
    def calendar_id(self, calendar_id):
        """Sets the calendar_id of this CalendarUpdateCalendarRequest.

        The ID of the calendar that is to be updated.  Required.  # noqa: E501

        :param calendar_id: The calendar_id of this CalendarUpdateCalendarRequest.  # noqa: E501
        :type: str
        """
        if calendar_id is None:
            raise ValueError("Invalid value for `calendar_id`, must not be `None`")  # noqa: E501

        self._calendar_id = calendar_id

    @property
    def calendar(self):
        """Gets the calendar of this CalendarUpdateCalendarRequest.  # noqa: E501


        :return: The calendar of this CalendarUpdateCalendarRequest.  # noqa: E501
        :rtype: CalendarCalendar
        """
        return self._calendar

    @calendar.setter
    def calendar(self, calendar):
        """Sets the calendar of this CalendarUpdateCalendarRequest.


        :param calendar: The calendar of this CalendarUpdateCalendarRequest.  # noqa: E501
        :type: CalendarCalendar
        """
        if calendar is None:
            raise ValueError("Invalid value for `calendar`, must not be `None`")  # noqa: E501

        self._calendar = calendar

    @property
    def update_mask(self):
        """Gets the update_mask of this CalendarUpdateCalendarRequest.  # noqa: E501


        :return: The update_mask of this CalendarUpdateCalendarRequest.  # noqa: E501
        :rtype: ProtobufFieldMask
        """
        return self._update_mask

    @update_mask.setter
    def update_mask(self, update_mask):
        """Sets the update_mask of this CalendarUpdateCalendarRequest.


        :param update_mask: The update_mask of this CalendarUpdateCalendarRequest.  # noqa: E501
        :type: ProtobufFieldMask
        """
        if update_mask is None:
            raise ValueError("Invalid value for `update_mask`, must not be `None`")  # noqa: E501

        self._update_mask = update_mask

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CalendarUpdateCalendarRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CalendarUpdateCalendarRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
