# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContractModulesListContractModuleVersionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contract_module_versions': 'list[ContractModulesContractModuleVersion]',
        'next_page_token': 'str',
        'previous_page_token': 'str'
    }

    attribute_map = {
        'contract_module_versions': 'contract_module_versions',
        'next_page_token': 'next_page_token',
        'previous_page_token': 'previous_page_token'
    }

    def __init__(self, contract_module_versions=None, next_page_token=None, previous_page_token=None):  # noqa: E501
        """ContractModulesListContractModuleVersionsResponse - a model defined in Swagger"""  # noqa: E501
        self._contract_module_versions = None
        self._next_page_token = None
        self._previous_page_token = None
        self.discriminator = None
        if contract_module_versions is not None:
            self.contract_module_versions = contract_module_versions
        if next_page_token is not None:
            self.next_page_token = next_page_token
        if previous_page_token is not None:
            self.previous_page_token = previous_page_token

    @property
    def contract_module_versions(self):
        """Gets the contract_module_versions of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501

        A list of Contract Module Versions, ordered by descending creation timestamp.  # noqa: E501

        :return: The contract_module_versions of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :rtype: list[ContractModulesContractModuleVersion]
        """
        return self._contract_module_versions

    @contract_module_versions.setter
    def contract_module_versions(self, contract_module_versions):
        """Sets the contract_module_versions of this ContractModulesListContractModuleVersionsResponse.

        A list of Contract Module Versions, ordered by descending creation timestamp.  # noqa: E501

        :param contract_module_versions: The contract_module_versions of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :type: list[ContractModulesContractModuleVersion]
        """

        self._contract_module_versions = contract_module_versions

    @property
    def next_page_token(self):
        """Gets the next_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501

        The token used to retrieve the next page. If empty, this returns the last page of results.  # noqa: E501

        :return: The next_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this ContractModulesListContractModuleVersionsResponse.

        The token used to retrieve the next page. If empty, this returns the last page of results.  # noqa: E501

        :param next_page_token: The next_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    @property
    def previous_page_token(self):
        """Gets the previous_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501

        The token used to retrieve the previous page. If empty, this returns the first page of results.  # noqa: E501

        :return: The previous_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :rtype: str
        """
        return self._previous_page_token

    @previous_page_token.setter
    def previous_page_token(self, previous_page_token):
        """Sets the previous_page_token of this ContractModulesListContractModuleVersionsResponse.

        The token used to retrieve the previous page. If empty, this returns the first page of results.  # noqa: E501

        :param previous_page_token: The previous_page_token of this ContractModulesListContractModuleVersionsResponse.  # noqa: E501
        :type: str
        """

        self._previous_page_token = previous_page_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContractModulesListContractModuleVersionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContractModulesListContractModuleVersionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
