# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContractModulesBatchGetContractModulesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contract_modules': 'dict(str, ContractModulesContractModule)'
    }

    attribute_map = {
        'contract_modules': 'contract_modules'
    }

    def __init__(self, contract_modules=None):  # noqa: E501
        """ContractModulesBatchGetContractModulesResponse - a model defined in Swagger"""  # noqa: E501
        self._contract_modules = None
        self.discriminator = None
        if contract_modules is not None:
            self.contract_modules = contract_modules

    @property
    def contract_modules(self):
        """Gets the contract_modules of this ContractModulesBatchGetContractModulesResponse.  # noqa: E501

        Map of ID to Contract Module.  # noqa: E501

        :return: The contract_modules of this ContractModulesBatchGetContractModulesResponse.  # noqa: E501
        :rtype: dict(str, ContractModulesContractModule)
        """
        return self._contract_modules

    @contract_modules.setter
    def contract_modules(self, contract_modules):
        """Sets the contract_modules of this ContractModulesBatchGetContractModulesResponse.

        Map of ID to Contract Module.  # noqa: E501

        :param contract_modules: The contract_modules of this ContractModulesBatchGetContractModulesResponse.  # noqa: E501
        :type: dict(str, ContractModulesContractModule)
        """

        self._contract_modules = contract_modules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContractModulesBatchGetContractModulesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContractModulesBatchGetContractModulesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
