# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FlagsFlag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'flag_definition_id': 'str',
        'description': 'str',
        'creation_timestamp': 'datetime',
        'effective_timestamp': 'datetime',
        'expiry_timestamp': 'datetime',
        'is_active': 'bool',
        'customer_id': 'CustomerId',
        'account_id': 'AccountId',
        'payment_device_id': 'PaymentDeviceId'
    }

    attribute_map = {
        'id': 'id',
        'flag_definition_id': 'flag_definition_id',
        'description': 'description',
        'creation_timestamp': 'creation_timestamp',
        'effective_timestamp': 'effective_timestamp',
        'expiry_timestamp': 'expiry_timestamp',
        'is_active': 'is_active',
        'customer_id': 'customer_id',
        'account_id': 'account_id',
        'payment_device_id': 'payment_device_id'
    }

    def __init__(self, id=None, flag_definition_id=None, description=None, creation_timestamp=None, effective_timestamp=None, expiry_timestamp=None, is_active=None, customer_id=None, account_id=None, payment_device_id=None):  # noqa: E501
        """FlagsFlag - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._flag_definition_id = None
        self._description = None
        self._creation_timestamp = None
        self._effective_timestamp = None
        self._expiry_timestamp = None
        self._is_active = None
        self._customer_id = None
        self._account_id = None
        self._payment_device_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if flag_definition_id is not None:
            self.flag_definition_id = flag_definition_id
        if description is not None:
            self.description = description
        if creation_timestamp is not None:
            self.creation_timestamp = creation_timestamp
        if effective_timestamp is not None:
            self.effective_timestamp = effective_timestamp
        if expiry_timestamp is not None:
            self.expiry_timestamp = expiry_timestamp
        if is_active is not None:
            self.is_active = is_active
        if customer_id is not None:
            self.customer_id = customer_id
        if account_id is not None:
            self.account_id = account_id
        if payment_device_id is not None:
            self.payment_device_id = payment_device_id

    @property
    def id(self):
        """Gets the id of this FlagsFlag.  # noqa: E501

        The ID of the flag. Output only.  # noqa: E501

        :return: The id of this FlagsFlag.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FlagsFlag.

        The ID of the flag. Output only.  # noqa: E501

        :param id: The id of this FlagsFlag.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def flag_definition_id(self):
        """Gets the flag_definition_id of this FlagsFlag.  # noqa: E501

        The ID of the flag definition. Required for create requests.  # noqa: E501

        :return: The flag_definition_id of this FlagsFlag.  # noqa: E501
        :rtype: str
        """
        return self._flag_definition_id

    @flag_definition_id.setter
    def flag_definition_id(self, flag_definition_id):
        """Sets the flag_definition_id of this FlagsFlag.

        The ID of the flag definition. Required for create requests.  # noqa: E501

        :param flag_definition_id: The flag_definition_id of this FlagsFlag.  # noqa: E501
        :type: str
        """

        self._flag_definition_id = flag_definition_id

    @property
    def description(self):
        """Gets the description of this FlagsFlag.  # noqa: E501

        The description of the flag. Required for create requests.  # noqa: E501

        :return: The description of this FlagsFlag.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FlagsFlag.

        The description of the flag. Required for create requests.  # noqa: E501

        :param description: The description of this FlagsFlag.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def creation_timestamp(self):
        """Gets the creation_timestamp of this FlagsFlag.  # noqa: E501

        The timestamp indicating when the flag was created. Output only.  # noqa: E501

        :return: The creation_timestamp of this FlagsFlag.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):
        """Sets the creation_timestamp of this FlagsFlag.

        The timestamp indicating when the flag was created. Output only.  # noqa: E501

        :param creation_timestamp: The creation_timestamp of this FlagsFlag.  # noqa: E501
        :type: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def effective_timestamp(self):
        """Gets the effective_timestamp of this FlagsFlag.  # noqa: E501

        The timestamp indicating when the flag was activated. Optional for create requests; must be set to a future time.   # noqa: E501

        :return: The effective_timestamp of this FlagsFlag.  # noqa: E501
        :rtype: datetime
        """
        return self._effective_timestamp

    @effective_timestamp.setter
    def effective_timestamp(self, effective_timestamp):
        """Sets the effective_timestamp of this FlagsFlag.

        The timestamp indicating when the flag was activated. Optional for create requests; must be set to a future time.   # noqa: E501

        :param effective_timestamp: The effective_timestamp of this FlagsFlag.  # noqa: E501
        :type: datetime
        """

        self._effective_timestamp = effective_timestamp

    @property
    def expiry_timestamp(self):
        """Gets the expiry_timestamp of this FlagsFlag.  # noqa: E501

        The timestamp indicating when the flag was deactivated. Optional for create requests; must be set to after the effective timestamp time.   # noqa: E501

        :return: The expiry_timestamp of this FlagsFlag.  # noqa: E501
        :rtype: datetime
        """
        return self._expiry_timestamp

    @expiry_timestamp.setter
    def expiry_timestamp(self, expiry_timestamp):
        """Sets the expiry_timestamp of this FlagsFlag.

        The timestamp indicating when the flag was deactivated. Optional for create requests; must be set to after the effective timestamp time.   # noqa: E501

        :param expiry_timestamp: The expiry_timestamp of this FlagsFlag.  # noqa: E501
        :type: datetime
        """

        self._expiry_timestamp = expiry_timestamp

    @property
    def is_active(self):
        """Gets the is_active of this FlagsFlag.  # noqa: E501

        Indicates if the flag is active. Update only.  # noqa: E501

        :return: The is_active of this FlagsFlag.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this FlagsFlag.

        Indicates if the flag is active. Update only.  # noqa: E501

        :param is_active: The is_active of this FlagsFlag.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def customer_id(self):
        """Gets the customer_id of this FlagsFlag.  # noqa: E501


        :return: The customer_id of this FlagsFlag.  # noqa: E501
        :rtype: CustomerId
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this FlagsFlag.


        :param customer_id: The customer_id of this FlagsFlag.  # noqa: E501
        :type: CustomerId
        """

        self._customer_id = customer_id

    @property
    def account_id(self):
        """Gets the account_id of this FlagsFlag.  # noqa: E501


        :return: The account_id of this FlagsFlag.  # noqa: E501
        :rtype: AccountId
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this FlagsFlag.


        :param account_id: The account_id of this FlagsFlag.  # noqa: E501
        :type: AccountId
        """

        self._account_id = account_id

    @property
    def payment_device_id(self):
        """Gets the payment_device_id of this FlagsFlag.  # noqa: E501


        :return: The payment_device_id of this FlagsFlag.  # noqa: E501
        :rtype: PaymentDeviceId
        """
        return self._payment_device_id

    @payment_device_id.setter
    def payment_device_id(self, payment_device_id):
        """Sets the payment_device_id of this FlagsFlag.


        :param payment_device_id: The payment_device_id of this FlagsFlag.  # noqa: E501
        :type: PaymentDeviceId
        """

        self._payment_device_id = payment_device_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FlagsFlag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlagsFlag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
