# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FlagsBatchGetFlagDefinitionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flag_definitions': 'dict(str, FlagsFlagDefinition)'
    }

    attribute_map = {
        'flag_definitions': 'flag_definitions'
    }

    def __init__(self, flag_definitions=None):  # noqa: E501
        """FlagsBatchGetFlagDefinitionsResponse - a model defined in Swagger"""  # noqa: E501
        self._flag_definitions = None
        self.discriminator = None
        if flag_definitions is not None:
            self.flag_definitions = flag_definitions

    @property
    def flag_definitions(self):
        """Gets the flag_definitions of this FlagsBatchGetFlagDefinitionsResponse.  # noqa: E501

        Maps requested flag definition IDs to their flag definitions.  # noqa: E501

        :return: The flag_definitions of this FlagsBatchGetFlagDefinitionsResponse.  # noqa: E501
        :rtype: dict(str, FlagsFlagDefinition)
        """
        return self._flag_definitions

    @flag_definitions.setter
    def flag_definitions(self, flag_definitions):
        """Sets the flag_definitions of this FlagsBatchGetFlagDefinitionsResponse.

        Maps requested flag definition IDs to their flag definitions.  # noqa: E501

        :param flag_definitions: The flag_definitions of this FlagsBatchGetFlagDefinitionsResponse.  # noqa: E501
        :type: dict(str, FlagsFlagDefinition)
        """

        self._flag_definitions = flag_definitions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FlagsBatchGetFlagDefinitionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlagsBatchGetFlagDefinitionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
