# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GlobalParametersCreateGlobalParameterRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_id': 'str',
        'global_parameter': 'GlobalParametersGlobalParameter',
        'initial_value': 'str'
    }

    attribute_map = {
        'request_id': 'request_id',
        'global_parameter': 'global_parameter',
        'initial_value': 'initial_value'
    }

    def __init__(self, request_id=None, global_parameter=None, initial_value=None):  # noqa: E501
        """GlobalParametersCreateGlobalParameterRequest - a model defined in Swagger"""  # noqa: E501
        self._request_id = None
        self._global_parameter = None
        self._initial_value = None
        self.discriminator = None
        self.request_id = request_id
        self.global_parameter = global_parameter
        self.initial_value = initial_value

    @property
    def request_id(self):
        """Gets the request_id of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501

        A unique string ID used for idempotency.  Required.  # noqa: E501

        :return: The request_id of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this GlobalParametersCreateGlobalParameterRequest.

        A unique string ID used for idempotency.  Required.  # noqa: E501

        :param request_id: The request_id of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def global_parameter(self):
        """Gets the global_parameter of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501


        :return: The global_parameter of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :rtype: GlobalParametersGlobalParameter
        """
        return self._global_parameter

    @global_parameter.setter
    def global_parameter(self, global_parameter):
        """Sets the global_parameter of this GlobalParametersCreateGlobalParameterRequest.


        :param global_parameter: The global_parameter of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :type: GlobalParametersGlobalParameter
        """
        if global_parameter is None:
            raise ValueError("Invalid value for `global_parameter`, must not be `None`")  # noqa: E501

        self._global_parameter = global_parameter

    @property
    def initial_value(self):
        """Gets the initial_value of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501

        This will be used to create a `GlobalParameterValue` associated with the newly created `GlobalParameter`. The `effective_timestamp` of the created `GlobalParameterValue` will be the Unix epoch.  Required.  # noqa: E501

        :return: The initial_value of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :rtype: str
        """
        return self._initial_value

    @initial_value.setter
    def initial_value(self, initial_value):
        """Sets the initial_value of this GlobalParametersCreateGlobalParameterRequest.

        This will be used to create a `GlobalParameterValue` associated with the newly created `GlobalParameter`. The `effective_timestamp` of the created `GlobalParameterValue` will be the Unix epoch.  Required.  # noqa: E501

        :param initial_value: The initial_value of this GlobalParametersCreateGlobalParameterRequest.  # noqa: E501
        :type: str
        """
        if initial_value is None:
            raise ValueError("Invalid value for `initial_value`, must not be `None`")  # noqa: E501

        self._initial_value = initial_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalParametersCreateGlobalParameterRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalParametersCreateGlobalParameterRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
