# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ParamsDateField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'ParamsDateType',
        'start': 'ParamsDate',
        'end': 'ParamsDate'
    }

    attribute_map = {
        'type': 'type',
        'start': 'start',
        'end': 'end'
    }

    def __init__(self, type=None, start=None, end=None):  # noqa: E501
        """ParamsDateField - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._start = None
        self._end = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end

    @property
    def type(self):
        """Gets the type of this ParamsDateField.  # noqa: E501


        :return: The type of this ParamsDateField.  # noqa: E501
        :rtype: ParamsDateType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ParamsDateField.


        :param type: The type of this ParamsDateField.  # noqa: E501
        :type: ParamsDateType
        """

        self._type = type

    @property
    def start(self):
        """Gets the start of this ParamsDateField.  # noqa: E501


        :return: The start of this ParamsDateField.  # noqa: E501
        :rtype: ParamsDate
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this ParamsDateField.


        :param start: The start of this ParamsDateField.  # noqa: E501
        :type: ParamsDate
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this ParamsDateField.  # noqa: E501


        :return: The end of this ParamsDateField.  # noqa: E501
        :rtype: ParamsDate
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this ParamsDateField.


        :param end: The end of this ParamsDateField.  # noqa: E501
        :type: ParamsDate
        """

        self._end = end

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ParamsDateField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParamsDateField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
