# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlansBatchGetPlanMigrationsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan_migrations': 'dict(str, PlansPlanMigration)'
    }

    attribute_map = {
        'plan_migrations': 'plan_migrations'
    }

    def __init__(self, plan_migrations=None):  # noqa: E501
        """PlansBatchGetPlanMigrationsResponse - a model defined in Swagger"""  # noqa: E501
        self._plan_migrations = None
        self.discriminator = None
        if plan_migrations is not None:
            self.plan_migrations = plan_migrations

    @property
    def plan_migrations(self):
        """Gets the plan_migrations of this PlansBatchGetPlanMigrationsResponse.  # noqa: E501

        A map of the plan migration ID to the plan migration.  # noqa: E501

        :return: The plan_migrations of this PlansBatchGetPlanMigrationsResponse.  # noqa: E501
        :rtype: dict(str, PlansPlanMigration)
        """
        return self._plan_migrations

    @plan_migrations.setter
    def plan_migrations(self, plan_migrations):
        """Sets the plan_migrations of this PlansBatchGetPlanMigrationsResponse.

        A map of the plan migration ID to the plan migration.  # noqa: E501

        :param plan_migrations: The plan_migrations of this PlansBatchGetPlanMigrationsResponse.  # noqa: E501
        :type: dict(str, PlansPlanMigration)
        """

        self._plan_migrations = plan_migrations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlansBatchGetPlanMigrationsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlansBatchGetPlanMigrationsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
