# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PostingsApiClientsPostingsAPIClient(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'response_topic': 'str',
        'response_topic_low_priority': 'str'
    }

    attribute_map = {
        'id': 'id',
        'response_topic': 'response_topic',
        'response_topic_low_priority': 'response_topic_low_priority'
    }

    def __init__(self, id=None, response_topic=None, response_topic_low_priority=None):  # noqa: E501
        """PostingsApiClientsPostingsAPIClient - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._response_topic = None
        self._response_topic_low_priority = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if response_topic is not None:
            self.response_topic = response_topic
        if response_topic_low_priority is not None:
            self.response_topic_low_priority = response_topic_low_priority

    @property
    def id(self):
        """Gets the id of this PostingsApiClientsPostingsAPIClient.  # noqa: E501

        A unique ID that identifies a `PostingsAPIClient` to the Postings API.  # noqa: E501

        :return: The id of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PostingsApiClientsPostingsAPIClient.

        A unique ID that identifies a `PostingsAPIClient` to the Postings API.  # noqa: E501

        :param id: The id of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def response_topic(self):
        """Gets the response_topic of this PostingsApiClientsPostingsAPIClient.  # noqa: E501

        The Kafka topic that the Postings API should respond to for this `PostingsAPIClient`. NOTES: - Multiple `PostingsAPIClient`s may share a response topic. - Must contain the prefix 'integration.'. For compatibility, existing topics that are not prefixed with 'integration.' are allowed.  # noqa: E501

        :return: The response_topic of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :rtype: str
        """
        return self._response_topic

    @response_topic.setter
    def response_topic(self, response_topic):
        """Sets the response_topic of this PostingsApiClientsPostingsAPIClient.

        The Kafka topic that the Postings API should respond to for this `PostingsAPIClient`. NOTES: - Multiple `PostingsAPIClient`s may share a response topic. - Must contain the prefix 'integration.'. For compatibility, existing topics that are not prefixed with 'integration.' are allowed.  # noqa: E501

        :param response_topic: The response_topic of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :type: str
        """

        self._response_topic = response_topic

    @property
    def response_topic_low_priority(self):
        """Gets the response_topic_low_priority of this PostingsApiClientsPostingsAPIClient.  # noqa: E501

        The low priority Kafka topic that the Postings API should respond to for this `PostingsAPIClient`. NOTES: - Multiple `PostingsAPIClient`s may share a response topic. - Must contain the prefix 'integration.'. For compatibility, existing topics that are not prefixed with 'integration.' are allowed.  # noqa: E501

        :return: The response_topic_low_priority of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :rtype: str
        """
        return self._response_topic_low_priority

    @response_topic_low_priority.setter
    def response_topic_low_priority(self, response_topic_low_priority):
        """Sets the response_topic_low_priority of this PostingsApiClientsPostingsAPIClient.

        The low priority Kafka topic that the Postings API should respond to for this `PostingsAPIClient`. NOTES: - Multiple `PostingsAPIClient`s may share a response topic. - Must contain the prefix 'integration.'. For compatibility, existing topics that are not prefixed with 'integration.' are allowed.  # noqa: E501

        :param response_topic_low_priority: The response_topic_low_priority of this PostingsApiClientsPostingsAPIClient.  # noqa: E501
        :type: str
        """

        self._response_topic_low_priority = response_topic_low_priority

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostingsApiClientsPostingsAPIClient, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostingsApiClientsPostingsAPIClient):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
