# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1AccountViolation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'payment_device_token': 'str',
        'type': 'V1AccountViolationType'
    }

    attribute_map = {
        'account_id': 'account_id',
        'payment_device_token': 'payment_device_token',
        'type': 'type'
    }

    def __init__(self, account_id=None, payment_device_token=None, type=None):  # noqa: E501
        """V1AccountViolation - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._payment_device_token = None
        self._type = None
        self.discriminator = None
        if account_id is not None:
            self.account_id = account_id
        if payment_device_token is not None:
            self.payment_device_token = payment_device_token
        if type is not None:
            self.type = type

    @property
    def account_id(self):
        """Gets the account_id of this V1AccountViolation.  # noqa: E501

        The ID of the account affected by the violation.  # noqa: E501

        :return: The account_id of this V1AccountViolation.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this V1AccountViolation.

        The ID of the account affected by the violation.  # noqa: E501

        :param account_id: The account_id of this V1AccountViolation.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def payment_device_token(self):
        """Gets the payment_device_token of this V1AccountViolation.  # noqa: E501

        The payment device token affected by the violation.  # noqa: E501

        :return: The payment_device_token of this V1AccountViolation.  # noqa: E501
        :rtype: str
        """
        return self._payment_device_token

    @payment_device_token.setter
    def payment_device_token(self, payment_device_token):
        """Sets the payment_device_token of this V1AccountViolation.

        The payment device token affected by the violation.  # noqa: E501

        :param payment_device_token: The payment_device_token of this V1AccountViolation.  # noqa: E501
        :type: str
        """

        self._payment_device_token = payment_device_token

    @property
    def type(self):
        """Gets the type of this V1AccountViolation.  # noqa: E501


        :return: The type of this V1AccountViolation.  # noqa: E501
        :rtype: V1AccountViolationType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1AccountViolation.


        :param type: The type of this V1AccountViolation.  # noqa: E501
        :type: V1AccountViolationType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AccountViolation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AccountViolation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
