# coding: utf-8

"""
    vault/kernel/core_api/proto/v1/accounts/core_api_account_schedule_tags.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1Posting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'credit': 'bool',
        'amount': 'str',
        'denomination': 'str',
        'account_id': 'str',
        'account_address': 'str',
        'asset': 'str',
        'phase': 'V1PostingPhase'
    }

    attribute_map = {
        'credit': 'credit',
        'amount': 'amount',
        'denomination': 'denomination',
        'account_id': 'account_id',
        'account_address': 'account_address',
        'asset': 'asset',
        'phase': 'phase'
    }

    def __init__(self, credit=None, amount=None, denomination=None, account_id=None, account_address=None, asset=None, phase=None):  # noqa: E501
        """V1Posting - a model defined in Swagger"""  # noqa: E501
        self._credit = None
        self._amount = None
        self._denomination = None
        self._account_id = None
        self._account_address = None
        self._asset = None
        self._phase = None
        self.discriminator = None
        if credit is not None:
            self.credit = credit
        if amount is not None:
            self.amount = amount
        if denomination is not None:
            self.denomination = denomination
        if account_id is not None:
            self.account_id = account_id
        if account_address is not None:
            self.account_address = account_address
        if asset is not None:
            self.asset = asset
        if phase is not None:
            self.phase = phase

    @property
    def credit(self):
        """Gets the credit of this V1Posting.  # noqa: E501

        Indicates whether the posting is a credit or debit.  # noqa: E501

        :return: The credit of this V1Posting.  # noqa: E501
        :rtype: bool
        """
        return self._credit

    @credit.setter
    def credit(self, credit):
        """Sets the credit of this V1Posting.

        Indicates whether the posting is a credit or debit.  # noqa: E501

        :param credit: The credit of this V1Posting.  # noqa: E501
        :type: bool
        """

        self._credit = credit

    @property
    def amount(self):
        """Gets the amount of this V1Posting.  # noqa: E501

        The posting amount.  # noqa: E501

        :return: The amount of this V1Posting.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this V1Posting.

        The posting amount.  # noqa: E501

        :param amount: The amount of this V1Posting.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def denomination(self):
        """Gets the denomination of this V1Posting.  # noqa: E501

        The posting denomination.  # noqa: E501

        :return: The denomination of this V1Posting.  # noqa: E501
        :rtype: str
        """
        return self._denomination

    @denomination.setter
    def denomination(self, denomination):
        """Sets the denomination of this V1Posting.

        The posting denomination.  # noqa: E501

        :param denomination: The denomination of this V1Posting.  # noqa: E501
        :type: str
        """

        self._denomination = denomination

    @property
    def account_id(self):
        """Gets the account_id of this V1Posting.  # noqa: E501

        The ID of the Vault account being posted to.  # noqa: E501

        :return: The account_id of this V1Posting.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this V1Posting.

        The ID of the Vault account being posted to.  # noqa: E501

        :param account_id: The account_id of this V1Posting.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def account_address(self):
        """Gets the account_address of this V1Posting.  # noqa: E501

        The address of the Vault account being posted to.  # noqa: E501

        :return: The account_address of this V1Posting.  # noqa: E501
        :rtype: str
        """
        return self._account_address

    @account_address.setter
    def account_address(self, account_address):
        """Sets the account_address of this V1Posting.

        The address of the Vault account being posted to.  # noqa: E501

        :param account_address: The account_address of this V1Posting.  # noqa: E501
        :type: str
        """

        self._account_address = account_address

    @property
    def asset(self):
        """Gets the asset of this V1Posting.  # noqa: E501

        The asset value of the posting.  # noqa: E501

        :return: The asset of this V1Posting.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this V1Posting.

        The asset value of the posting.  # noqa: E501

        :param asset: The asset of this V1Posting.  # noqa: E501
        :type: str
        """

        self._asset = asset

    @property
    def phase(self):
        """Gets the phase of this V1Posting.  # noqa: E501


        :return: The phase of this V1Posting.  # noqa: E501
        :rtype: V1PostingPhase
        """
        return self._phase

    @phase.setter
    def phase(self, phase):
        """Sets the phase of this V1Posting.


        :param phase: The phase of this V1Posting.  # noqa: E501
        :type: V1PostingPhase
        """

        self._phase = phase

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1Posting, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1Posting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
