python_test(
    name = "test_postings",
    srcs = ["test_postings.py"],
    data = [
    ],
    labels = ["unit"],
    deps = [
        "//common/test_utils/endtoend",
        "//common/test_utils/endtoend:contracts_helper",
        "//common/test_utils/endtoend:core_api_helper",
        "//common/test_utils/endtoend:helper",
        "//common/test_utils/endtoend:postings",
        "//common/test_utils/postings:posting_classes",
        "//third_party/python3:pyyaml",
    ],
)
