filegroup(
    name="balance_update_event",
    srcs=["sample_balance_update_event.json"],
    visibility=["PUBLIC"],
)

filegroup(
    name="wf_instantiation_event",
    srcs=["sample_wf_instantiation_event.json"],
    visibility=["PUBLIC"],
)