filegroup(
    name="normal_plan_associations",
    srcs=[
        "normal_plan_associations.json",
    ],
    visibility=["PUBLIC"],
)

filegroup(
    name="multi_plan_associations",
    srcs=[
        "multi_plan_associations.json",
    ],
    visibility=["PUBLIC"],
)

filegroup(
    name = "wf_message_event",
    srcs = ["sample_wf_instantiation_event.json"],
    visibility = [
        "PUBLIC"
    ]
)
