python_library(
    name = "empty_contract",
    srcs = ["empty_contract.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "full_contract",
    srcs = ["full_contract.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "full_contract_updated_version",
    srcs = ["full_contract_updated_version.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "supervisor_contract",
    srcs = ["supervisor_contract.py"],
    visibility = [
        "PUBLIC"
    ],
)


python_library(
    name = "supervised_checking_account",
    srcs = ["supervised_checking_account.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "supervised_checking_account_with_contract_modules",
    srcs = ["supervised_checking_account_with_contract_modules.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "supervised_savings_deposit_account",
    srcs = ["supervised_savings_deposit_account.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "supervised_savings_deposit_account_with_contract_modules",
    srcs = ["supervised_savings_deposit_account_with_contract_modules.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "supervised_youth_account",
    srcs = ["supervised_youth_account.py"],
    visibility = [
        "PUBLIC"
    ],
)
