python_library(
    name = "file_utils",
    srcs = ["file_utils.py"],
    visibility = ["PUBLIC"],
    deps = [
        ":resources"
    ]
)

python_library(
    name = "flag_utils",
    srcs = ["flag_utils.py"],
    visibility = ["PUBLIC"]
)

python_library(
    name = "resources",
    srcs = ["resources.py"],
    visibility = ["PUBLIC"]
)

python_library(
    name = "so_import",
    srcs = ["so_import.py"],
    deps = [
        ":resources",
    ],
    visibility = ["PUBLIC"]
)
