python_library(
    name = "contract_module",
    srcs = ["contract_module.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "contract_module_2",
    srcs = ["contract_module_2.py"],
    visibility = [
        "PUBLIC"
    ],
)

python_library(
    name = "full_contract_with_shared_function",
    srcs = ["full_contract_with_shared_function.py"],
    visibility = [
        "PUBLIC"
    ],
)